### ISSUE TITLE
"Fetch failed" of what exactly ?

### ISSUE THREAD

**Issue by pligor** [Mintplex-Labs/anything-llm#127]
Many thanks for all the fixes announced today.

Using Macbook M2 Pro (Apple Silicon Chip)

Rebuilt everything from scratch using this command:
`docker-compose down && docker-compose build --no-cache && docker-compose up -d`

This issue is clear in this screenshot: 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/1448173/94abef99-1913-4760-b0dc-949633dc97b3)

Cannot make sense if the root cause is that the system is failing to connect to websockets, or whether something else is not working
By the way how could the system connect to localhost:3000 for websockets ? I believe there is nothing listening in port 3000 and the docker configuration is not suggesting this port to be used for any connections..

Fyi System Settings seem to be setup ok

![image](https://github.com/Mintplex-Labs/anything-llm/assets/1448173/2364a873-a9d4-44d9-9f17-8f0dd53e02a5)

**Comment by timothycarambat** [comment]
fetch failed when using chroma is a nondescript error that the library returns which means the chroma instance is not accessible or not working

**Comment by pligor** [comment]
You are right. The default one is misleading.

We needed this one: `CHROMA_ENDPOINT='http://host.docker.internal:8000' # Allow docker to look on host port, not container.`

**Comment by nidupb** [comment]
I changed the .env to `CHROMA_ENDPOINT='http://host.docker.internal:8000'` though I have a similar error. Here is an extract of the docker log, not familiar how to solve that issue : 
```
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [13] [INFO] Starting gunicorn 20.1.0
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [13] [INFO] Listening at: http://0.0.0.0:8888 (13)
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [13] [INFO] Using worker: sync
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [22] [INFO] Booting worker with pid: 22
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [24] [INFO] Booting worker with pid: 24
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [26] [INFO] Booting worker with pid: 26
2023-08-02 15:04:07 [2023-08-02 19:04:07 +0000] [28] [INFO] Booting worker with pid: 28
2023-08-02 15:04:08 [MIGRATIONS STUBBED] Please ping /migrate once server starts to run migrations
2023-08-02 15:04:08 Example app listening on port 3001
2023-08-02 15:04:20 SELECT * FROM system_settings WHERE label = 'multi_user_mode'
2023-08-02 15:04:20 SELECT * FROM system_settings WHERE label = 'multi_user_mode'
2023-08-02 15:04:20 SELECT * FROM system_settings WHERE label = 'multi_user_mode'
2023-08-02 15:04:21 fetch failed TypeError: fetch failed
2023-08-02 15:04:21     at Object.fetch (node:internal/deps/undici/undici:11576:11)
2023-08-02 15:04:21     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-02 15:04:21     at async ChromaClient.heartbeat (/app/server/node_modules/chromadb/dist/main/ChromaClient.js:67:26)
2023-08-02 15:04:21     at async Object.connect (/app/server/utils/vectorDbProviders/chroma/index.js:23:21)
2023-08-02 15:04:21     at async Object.totalIndicies (/app/server/utils/vectorDbProviders/chroma/index.js:35:24)
2023-08-02 15:04:21     at async /app/server/endpoints/system.js:169:27 {
2023-08-02 15:04:21   cause: Error: connect ECONNREFUSED 192.168.65.254:8000
2023-08-02 15:04:21       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
2023-08-02 15:04:21     errno: -111,
2023-08-02 15:04:21     code: 'ECONNREFUSED',
2023-08-02 15:04:21     syscall: 'connect',
2023-08-02 15:04:21     address: '192.168.65.254',
2023-08-02 15:04:21     port: 8000
2023-08-02 15:04:21   }
2023-08-02 15:04:21 }
```

**Comment by nidupb** [comment]
For anyone running in the error, here is the complete video guide for using AnythingLLM with Chroma : https://www.youtube.com/watch?v=xRIEKjOosaM&t=558s
