### ISSUE TITLE
vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues Error: vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#141]
The error I'm getting is very similar to the one stated by @shrashansh
              vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues Error: vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues
    at getPlatformLibrary (/com.docker.devenvironments.code/server/node_modules/vectordb/native.js:25:15)
    at Object.<anonymous> (/com.docker.devenvironments.code/server/node_modules/vectordb/native.js:33:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/com.docker.devenvironments.code/server/node_modules/vectordb/dist/index.js:29:124)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

following issue. please help

_Originally posted by @shrashansh in https://github.com/Mintplex-Labs/anything-llm/issues/47#issuecomment-1605751077_

**Comment by jignnsd** [comment]
Hello, I'm using a ubuntu virtual machine running on a M1 Mac. I'm using pinecone as the DB, not lanceDB, anyway getting this message when trying to chat: 
vectordb: unsupported platform linux_arm64. Please file a bug report at vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues
any ideas? many thanks

**Comment by timothycarambat** [comment]
If this blocking the application from botting up? You should be able to just specify `pinecone` as the vector db in the settings and be done

**Comment by jignnsd** [comment]
> If this blocking the application from botting up? You should be able to just specify `pinecone` as the vector db in the settings and be done

I just change the computer that I was using, now it has a rocky Linux and running on an intel processor. Many thanks!
