### ISSUE TITLE
 Could not respond to message. Reason: OpenAI::CreateModeration failed with: Request failed with status code 429

### ISSUE THREAD

**Issue by twocoins-ca** [Mintplex-Labs/anything-llm#179]
Any tip will be much appreciated.

2023-08-04 13:06:50 fetch failed TypeError: fetch failed
2023-08-04 13:06:50     at Object.fetch (node:internal/deps/undici/undici:11576:11)
2023-08-04 13:06:50     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-08-04 13:06:50     at async ChromaClient.heartbeat (/app/server/node_modules/chromadb/dist/main/ChromaClient.js:67:26)
2023-08-04 13:06:50     at async Object.connect (/app/server/utils/vectorDbProviders/chroma/index.js:23:21)
2023-08-04 13:06:50     at async Object.totalIndicies (/app/server/utils/vectorDbProviders/chroma/index.js:35:24)
2023-08-04 13:06:50     at async /app/server/endpoints/system.js:169:27 {
2023-08-04 13:06:50   cause: Error: connect ECONNREFUSED 127.0.0.1:8000
2023-08-04 13:06:50       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
2023-08-04 13:06:50     errno: -111,
2023-08-04 13:06:50     code: 'ECONNREFUSED',
2023-08-04 13:06:50     syscall: 'connect',
2023-08-04 13:06:50     address: '127.0.0.1',
2023-08-04 13:06:50     port: 8000
2023-08-04 13:06:50   }
2023-08-04 13:06:50 }

**Comment by timothycarambat** [comment]
You are connected to a Chroma instance that should be running on 127.0.0.1:8000 that does not exist on such a URL.

If you are running AnythingLLM **and** Chroma in docker at the same time use `http://host.docker.internal:8000` as your URL. Otherwise if you are running AnythingLLM outside of a docker container ensure that you are running a chroma instance at `http://localhost:8000` and you should be able to hit `http://localhost:8000/api/v1/heartbeat` in your browser.
