### ISSUE TITLE
[BUG]: White screen on settings for Vector Database and Embedder

### ISSUE THREAD

**Issue by points-unknown** [Mintplex-Labs/anything-llm#2540]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Brand new instance of AnythingLLM on docker on remote virtual machine. Everything appears to work as expected except when I click on settings >> Vector Database or Embedder. Then I get a white screen. No more settings
Console log says:
```

index.js:40  TypeError: Cannot read properties of undefined (reading 'logo')
    at _e (index-b41a81d3.js:1:32581)
    at Mu (index.js:38:16997)
    at pc (index.js:40:3139)
    at S0 (index.js:40:44734)
    at A0 (index.js:40:39724)
    at fw (index.js:40:39652)
    at ts (index.js:40:39506)
    at Lc (index.js:40:35874)
    at w0 (index.js:40:34825)
    at k (index.js:25:1582)
dc @ index.js:40
n.callback @ index.js:40
ip @ index.js:38
Ap @ index.js:40
y0 @ index.js:40
dw @ index.js:40
gw @ index.js:40
hr @ index.js:40
w0 @ index.js:40
k @ index.js:25
Z @ index.js:25
index.js:40  Uncaught TypeError: Cannot read properties of undefined (reading 'logo')
    at _e (index-b41a81d3.js:1:32581)
    at Mu (index.js:38:16997)
    at pc (index.js:40:3139)
    at S0 (index.js:40:44734)
    at A0 (index.js:40:39724)
    at fw (index.js:40:39652)
    at ts (index.js:40:39506)
    at Lc (index.js:40:35874)
    at w0 (index.js:40:34825)
    at k (index.js:25:1582)
```

### Are there known steps to reproduce?

Launch docker container using all defaults.
Click on settings >> Vector Database 
or
Settings >> Embedder

Result: White screen. No settings.

**Comment by points-unknown** [comment]
Fixed my own issue. Consider taking the quotes out of the example .env file for docker. I removed all the quotes and now everything is working.
