### ISSUE TITLE
vectordb: unsupported platform win32_x64. Please file a bug report at https://github.com/lancedb/lancedb/issues Error: vectordb: unsupported platform win32_x64. Please file a bug report at https://github.com/lancedb/lancedb/issues

### ISSUE THREAD

**Issue by core116** [Mintplex-Labs/anything-llm#283]
```
vectordb: unsupported platform win32_x64. Please file a bug report at https://github.com/lancedb/lancedb/issues Error: vectordb: unsupported platform win32_x64. Please file a bug report at https://github.com/lancedb/lancedb/issues
    at getPlatformLibrary (D:\workspace\anything-llm\anything-llm\server\node_modules\vectordb\native.js:25:15)
    at Object.<anonymous> (D:\workspace\anything-llm\anything-llm\server\node_modules\vectordb\native.js:33:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\workspace\anything-llm\anything-llm\server\node_modules\vectordb\dist\index.js:29:172)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```
    
I run the project on local environment (windows) and i encountered this error.
please help me 🙏

**Comment by timothycarambat** [comment]
Swap your VectorDB to something other than lanceDB by default using the `VECTOR_DB` env variable. LanceDB was having issues with supporting windows for a minute. Not sure if that has changed because we have not bumped the version of LanceDB yet

**Comment by core116** [comment]
Hi @timothycarambat 
Thank you for your replay I tried to reinstall node module of lanceDB and it did work!

**Comment by j-loquat** [comment]
what command did you run to reinstall lanceDB to get it working? Thanks!

**Comment by timothycarambat** [comment]
@j-loquat if running on Docker - no action required.

If running locally you can `rm -rf server/node_modules` and then `cd server && yarn` This issue was limited to a specific version of LanceDB that did not include the windows binaries for LanceDB
