### ISSUE TITLE
Chat API broke in latest release

### ISSUE THREAD

**Issue by Britman72** [Mintplex-Labs/anything-llm#324]
When the chat API is called it crashes the Docker instance with:

2023-11-02 10:28:19 anything-llm  | /app/server/endpoints/api/workspace/index.js:495
2023-11-02 10:28:19 anything-llm  |           id: uuidv4(),
2023-11-02 10:28:19 anything-llm  |               ^
2023-11-02 10:28:19 anything-llm  | 
2023-11-02 10:28:19 anything-llm  | ReferenceError: uuidv4 is not defined
2023-11-02 10:28:19 anything-llm  |     at /app/server/endpoints/api/workspace/index.js:495:15
2023-11-02 10:28:19 anything-llm  | 
2023-11-02 10:28:19 anything-llm  | Node.js v18.18.2
anything-llm exited with code 1

**Comment by Britman72** [comment]
Closing this, was a mistake on my end.

**Comment by Britman72** [comment]
I am re-opening this. I thought it was due to me switching query mode to conversation mode in the API JSON string, but it turns out this issue is random and what looks like due to the prima query not returning or getting hung up. It seems to happen once in about a dozen queries and crashes the docker instance. Restarting the instance and issuing the same API call works but then fails randomly again.

2023-11-03 09:20:59 anything-llm  | prisma:query SELECT `main`.`workspace_chats`.`id`, `main`.`workspace_chats`.`workspaceId`, `main`.`workspace_chats`.`prompt`, `main`.`workspace_chats`.`response`, `main`.`workspace_chats`.`include`, `main`.`workspace_chats`.`user_id`, `main`.`workspace_chats`.`createdAt`, `main`.`workspace_chats`.`lastUpdatedAt` FROM `main`.`workspace_chats` WHERE (`main`.`workspace_chats`.`workspaceId` = ? AND `main`.`workspace_chats`.`include` = ?) ORDER BY `main`.`workspace_chats`.`id` DESC LIMIT ? OFFSET ?
2023-11-03 09:22:05 anything-llm  | /app/server/endpoints/api/workspace/index.js:495
2023-11-03 09:22:05 anything-llm  |           id: uuidv4(),
2023-11-03 09:22:05 anything-llm  |               ^
2023-11-03 09:22:05 anything-llm  | 
2023-11-03 09:22:05 anything-llm  | ReferenceError: uuidv4 is not defined
2023-11-03 09:22:05 anything-llm  |     at /app/server/endpoints/api/workspace/index.js:495:15
2023-11-03 09:22:05 anything-llm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-03 09:22:05 anything-llm  | 
2023-11-03 09:22:05 anything-llm  | Node.js v18.18.2
anything-llm exited with code 1
