### ISSUE TITLE
element-ui.js | Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')  

### ISSUE THREAD

**Issue by kaboomskizzle** [Mintplex-Labs/anything-llm#35]
Seems to be running a bit smoother now. Nothing is green in settings... Not sure how to switch to convo mode without unnattaching docs. No console errors. Does this prototype error actually worth sharing?
`ement-ui.js:1 Uncau'ght TypeError: Cannot read properties of undefined (reading 'prototype')
    at Module.<anonymous> (element-ui.js:1:127637)
    at n (element-ui.js:1:406)
    at Object.<anonymous> (element-ui.js:1:93343)
    at n (element-ui.js:1:406)
    at element-ui.js:1:1211
    at element-ui.js:1:1221
    at element-ui.js:1:234
    at element-ui.js:1:243
(`

**Comment by kaboomskizzle** [comment]
> This would be related to the ENV settings not being found. This is for sure related to something going on locally.
> 
> Are you on the latest commit of the main branch?

Ahh you got it whoops!
The .env was had an inconsistency with the .env.development
