### ISSUE TITLE
Debian glibc issue

### ISSUE THREAD

**Issue by simonSlamka** [Mintplex-Labs/anything-llm#39]
Hi,

First of all, great tool! Makes it easy to use an existing knowledge base and then dynamically ask about it using natural language. Wanted to build something like this myself, but you just saved me some time. Thank you!

But, after having fixed the requirements file as per #5, I have encountered an issue with libssl, which required manually building from source due to Debian not being a rolling distro. That fixed the libssl issue, but then, I encountered an issue with a version mismatch of glibc, which is apparently required by nodejs.

`uname -a`: `Linux hostname 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux`

```
yarn run v1.22.19
$ cd server && yarn dev
$ NODE_ENV=development nodemon --ignore documents --ignore vector-cache --trace-warnings index.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --trace-warnings index.js`
Example app listening on port 3001
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/<username>/git/anything-llm/server/node_modules/vectordb/x86_64-unknown-linux-gnu.node) Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/<username>/git/anything-llm/server/node_modules/vectordb/x86_64-unknown-linux-gnu.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at getPlatformLibrary (/home/<username>/git/anything-llm/server/node_modules/vectordb/native.js:23:16)
    at Object.<anonymous> (/home/<username>/git/anything-llm/server/node_modules/vectordb/native.js:33:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

This err is raised when the frontend is launched and opened in a browser. I haven't been able to fix the glibc issue, as opposed to libssl. I am afraid that it would mess up my Debian install.

Thanks

**Comment by frasergr** [comment]
I also had a bunch of issues when trying to get it running on a node Docker image which is based on Debian 11. I ended up using a recent Ubuntu LTS image and the issues went away. I think all the issues I encountered (and there were more than two you've come across) were related to the `vectordb` [package](https://www.npmjs.com/package/vectordb)

**Comment by simonSlamka** [comment]
Same issue under Ubuntu 20.04

```
..[$] <( (git)-[master]-)> yarn dev:server  
yarn run v1.22.19
$ cd server && yarn dev
$ NODE_ENV=development nodemon --ignore documents --ignore vector-cache --trace-warnings index.js
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node --trace-warnings index.js`
Example app listening on port 3001
libssl.so.3: cannot open shared object file: No such file or directory Error: libssl.so.3: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at getPlatformLibrary (/home/<username>/git/anything-llm/server/node_modules/vectordb/native.js:23:16)
    at Object.<anonymous> (/home/<username>/git/anything-llm/server/node_modules/vectordb/native.js:33:21)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}
SELECT * FROM workspaces 
```

I assume that the glibc issue would follow fixing this libssl issue, just like it did under my host (now running under distrobox).
`Linux ubuntu-20-04.hostname 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by frasergr** [comment]
By recent Ubuntu LTS I meant 22.04 :)

Have a look at the Dockerfile to see if it may point you in the right direction for your use case: https://github.com/Mintplex-Labs/anything-llm/blob/4e242a339fd934c1918dca65a097a1bc5eeca410/docker/Dockerfile

**Comment by simonSlamka** [comment]
Working for me under Debian 11 using [distrobox](https://github.com/89luca89/distrobox) to run Ubuntu 22.04.

Thanks, @frasergr!
