### ISSUE TITLE
Watch.PY Youtube Timeout

### ISSUE THREAD

**Issue by kaboomskizzle** [Mintplex-Labs/anything-llm#42]
Works for Substack and single page URLs but when I try for Youtube, after adding Cloud API I see:
`python3 main.py
? What kind of data would you like to add to convert into long-term memory?  YouTube Channel
Paste in the URL of a YouTube channel: https://www.youtube.com/@eyeonai3425
Need to map username to channelId - this can take a while sometimes.
Traceback (most recent call last):
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 406, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/sepad/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='yt.lemnoslife.com', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sepad/Documents/Apps/AnythingLLM/anything-llm-master/collector/main.py", line 81, in <module>
    main()
  File "/home/sepad/Documents/Apps/AnythingLLM/anything-llm-master/collector/main.py", line 65, in main
    youtube()
  File "/home/sepad/Documents/Apps/AnythingLLM/anything-llm-master/collector/scripts/youtube.py", line 13, in youtube
    channel_id = get_channel_id(channel_link)
  File "/home/sepad/Documents/Apps/AnythingLLM/anything-llm-master/collector/scripts/yt_utils.py", line 18, in get_channel_id
    response = requests.get(f"https://yt.lemnoslife.com/channels?handle={handle}", timeout=20)
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/sepad/.local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='yt.lemnoslife.com', port=443): Read timed out. (read timeout=20)
`
Do I need to increase timeout delay or is this because I'm on Linux?

Thanks!
Kaboom.ski

**Comment by frasergr** [comment]
I had these errors too and had to use the URL which includes the channel ID rather than the "@name" one.

**Comment by timothycarambat** [comment]
Ah yes, if you use the `@channel` URL we hit a third-party service that can do the transformation and it is **god awfully** slow to response. 

When you get this just go to the channel and then go to about and click on the share icon. You will see a channel ID option. Copy that and you should have a URL like `https://youtube.com/channel/xxxxxxx`
