### ISSUE TITLE
unable to load websites with recent version 

### ISSUE THREAD

**Issue by Anto79-ops** [Mintplex-Labs/anything-llm#453]
Hi!

When I try to add to add/embed a website, I get the following error:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/79593761/858a01fc-9214-4f48-b756-7126bc1c20fa)

and this log.

```
webui              | Primary server listening on port 3001
webui              | -- Working URL https://tea-cup.midori-ai.xyz/ --
webui              | getPageContent failed! Error: Failed to launch the browser process!
webui              | [166:166:1216/043726.499514:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
webui              |
webui              |
webui              | TROUBLESHOOTING: https://pptr.dev/troubleshooting
webui              |
webui              |     at ChildProcess.onClose (file:///app/collector/node_modules/@puppeteer/browsers/lib/esm/launch.js:268:24)
webui              |     at ChildProcess.emit (node:events:529:35)
webui              |     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
webui              | TypeError: Cannot read properties of null (reading 'length')
webui              |     at scrapeGenericUrl (/app/collector/processLink/convert/generic.js:13:16)
webui              |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
webui              |     at async processLink (/app/collector/processLink/index.js:6:10)
webui              |     at async /app/collector/index.js:47:33
```

seems to do it for all websites.

thanks for the great work!

**Comment by Anto79-ops** [comment]
all good,

needed to add this:

```
    cap_add:
      - SYS_ADMIN
```

and now works with websites!

thanks
