### ISSUE TITLE
Chat errors out

### ISSUE THREAD

**Issue by AkashCS** [Mintplex-Labs/anything-llm#47]
Installed successfully on Windows Docker Desktop.
Chroma Local Install is being used as Vector DB.
Docker build was successful.

Workspace created successfully.
Document loaded successful.

However when I try to chat, a message pops up as below...

localhost:3001 says 
Could not send chat

No other error or notification.
Gets no response in chat.

Kindly help.

**Comment by AkashCS** [comment]
![Anything-LLM-Error](https://github.com/Mintplex-Labs/anything-llm/assets/34915142/194fa75c-c747-4d81-8b40-eea5d02dfacd)

**Comment by lifuzu** [comment]
+1

**Comment by simonSlamka** [comment]
+1

**Comment by rewphus** [comment]
+1

**Comment by preeteshjain** [comment]
Attaching browser console logs for debugging

<img width="1436" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6207830/6af9e65f-076a-4948-958d-8ab06128ab33">

<img width="1437" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/6207830/20c485e8-f9af-45d2-8874-b3512a2b4595">

**Comment by simonSlamka** [comment]
```
SELECT * FROM workspaces WHERE slug = 'logs'
SELECT * FROM workspace_documents WHERE workspaceId = 5 
Request failed with status code 401 Error: Request failed with status code 401
    at createError (/Users/jacksparrow/anything-llm/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jacksparrow/anything-llm/server/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/jacksparrow/anything-llm/server/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'OpenAI/NodeJS/3.2.1',
      Authorization: 'Bearer undefined',
      'Content-Length': 88
    },
    method: 'post',
    data: '{"input":"why is Sören being distant? or, at least, why does it feel as if he were?\\n"}',
    url: 'https://api.openai.com/v1/moderations'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 88,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.openai.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.openai.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 4237,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 225,
        [Symbol(triggerId)]: 223
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /v1/moderations HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: OpenAI/NodeJS/3.2.1\r\n' +
      'Authorization: Bearer undefined\r\n' +
      'Content-Length: 88\r\n' +
      'Host: api.openai.com\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/v1/moderations',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.openai.com/v1/moderations',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 26,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.openai.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 88,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.openai.com/v1/moderations',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      authorization: [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      date: 'Thu, 15 Jun 2023 07:23:33 GMT',
      'content-type': 'application/json',
      'content-length': '238',
      connection: 'keep-alive',
      'www-authenticate': 'Basic realm="OpenAI API"',
      'openai-version': '2020-10-01',
      'x-request-id': '450ad2496708504841ba2e2ac0a1b8cd',
      'openai-processing-ms': '2',
      'strict-transport-security': 'max-age=15724800; includeSubDomains',
      'cf-cache-status': 'DYNAMIC',
      server: 'cloudflare',
      'cf-ray': '7d79117f2892abd5-CPH',
      'alt-svc': 'h3=":443"; ma=86400'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      data: '{"input":"text text text redacted text\\n"}',
      url: 'https://api.openai.com/v1/moderations'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 88,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /v1/moderations HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: OpenAI/NodeJS/3.2.1\r\n' +
        'Authorization: Bearer undefined\r\n' +
        'Content-Length: 88\r\n' +
        'Host: api.openai.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/moderations',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.openai.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
```

this is what I get when the chat errors out. also, why is the moderation API even used? isn't that optional? I remember when there was an option in the API to disable it

**Comment by veramarvin** [comment]
Hi, I'm experiencing the same error. I'm using Windows 11

**Comment by dennisnadeau** [comment]
+1 using Win 10

**Comment by sigpoggy** [comment]
I'm on intel mac with same problem - "Could not send chat."

**Comment by kolenyo2099** [comment]
With all things green, I'm having the same issue with a Mac M2. Everything else supposedly went well.

**Comment by tabgab** [comment]
Unfortunately, I get the same thing after fighting through the installation on a Mac M1.

**Comment by yaronsivan** [comment]
All things green, I'm having the same issue with a Mac M2. The installation and all worked well.

**Comment by subarudad** [comment]
+1 Mac M1

**Comment by jmmathieu** [comment]
same here, installed successfully in WSL2 using Docker instructions, all green, uploaded a test doc, now getting cannot send chat error.

**Comment by rhafiko** [comment]
yes, for me same message: cannot send chat error.

**Comment by jkrobin** [comment]
I'm getting the same "Could not send chat" on M1 Mac with docker install. All API variables show green in the UI.

I do see the following in the docker log:

`PineconeClient: Error calling describeIndex: 404: Not Found [PineconeError: PineconeClient: Error calling describeIndex: 404: Not Found]`

and 

```
SELECT * FROM workspaces WHERE slug = 'jkr-anything-test-1'
SELECT * FROM workspace_documents WHERE workspaceId = 1 
Request failed with status code 429 Error: Request failed with status code 429
    at createError (/app/server/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/server/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/server/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Any suggestions welcome!

**Comment by simonSlamka** [comment]
> I'm getting the same "Could not send chat" on M1 Mac with docker install. All API variables show green in the UI.
> 
> I do see the following in the docker log:
> 
> `PineconeClient: Error calling describeIndex: 404: Not Found [PineconeError: PineconeClient: Error calling describeIndex: 404: Not Found]`
> 
> and
> 
> ```
> SELECT * FROM workspaces WHERE slug = 'jkr-anything-test-1'
> SELECT * FROM workspace_documents WHERE workspaceId = 1 
> Request failed with status code 429 Error: Request failed with status code 429
>     at createError (/app/server/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/app/server/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/app/server/node_modules/axios/lib/adapters/http.js:322:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```
> 
> Any suggestions welcome!
> 
> ALSO... can someone tell me if the pinecone index name in .env should the short name (e.g. "anything-test") or the long name (e.g. "anything-test-2aa184a.svc.us-west1-gcp-free.pinecone.io") shown in the Pinecone console?
> 
> Thanks!

@jkrobin short name. also, I think your error is due to you picking the wrong name, since it seems to be erroring out due to a response from Pinecone and not the ui, if that makes sense

**Comment by ajosegun** [comment]
@jkrobin I had the same issue today.

I used the shortname i.e 'anything-test-2aa184a.svc.us-west1-gcp-free.pinecone.io' to '**anything-test**' for the index

**Comment by jkrobin** [comment]
Thanks to all for your input. My "Could not send chat" error was resolved after I found that my free OpenAI trial credits had expired. Once I set up a paid account on OpenAI the issue was resolved.

**Comment by tabgab** [comment]
Thanks to @torkati44 for the idea. The problem is that OpenAI is not ready to handle the requests, as you do not have enough credits. I switched to a different account, and it started working. On a regular trial account, or even a 20-dollar/month chat account, you are severely rate limited. 

| **MODEL** | **RPM** | **TPM** |
| --- | --- | --- |
| **CHAT** |
| gpt-3.5-turbo | 3 | 40,000 |

So it will throw an error. One, that is relatively uninformative, but this is the underlying cause.

Our corporate account on the other hand can do:

| **MODEL** | **RPM** | **TPM** |
| --- | --- | --- |
| CHAT |
| gpt-3.5-turbo | 3,500 | 90,000 |

And it works fine with that.

**Comment by pligor** [comment]
Our rate limits seem fine.
A screenshot from OpenAI platform webpage: 
https://platform.openai.com/account/rate-limits
<img width="963" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/1448173/d54c16ee-ea11-4f56-8054-3fba5cf57ddf">

Look what errors we get:
<img width="2538" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/1448173/d1eba9f2-3a50-4311-a5be-e35f6c4bad61">

ChromaDB is not going to work with AnythingLLM after all ? Or is it something else that is the root cause of this failure here ?

**Comment by shrashansh** [comment]
vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues Error: vectordb: unsupported platform linux_arm64. Please file a bug report at https://github.com/lancedb/lancedb/issues
    at getPlatformLibrary (/com.docker.devenvironments.code/server/node_modules/vectordb/native.js:25:15)
    at Object.<anonymous> (/com.docker.devenvironments.code/server/node_modules/vectordb/native.js:33:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/com.docker.devenvironments.code/server/node_modules/vectordb/dist/index.js:29:124)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)




following issue. please help

**Comment by timothycarambat** [comment]
The root cause is almost always that the .env is not setup properly or is missing values. 

latest changes allow you to set .env while app is running (for those who cannot seem to set them on boot for numerous reasons). Also we just improved error messages during chat which should let you know if the service is offline, and API key is invalid, or xyz.
