### ISSUE TITLE
yarn prod server on windows platform,print logs such as:

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#482]
The "paths[0]" argument must be of type string. Received undefined TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:167:9)
    at viewLocalFiles (\anything-llm\server\utils\files\index.js:51:14)     
    at \anything-llm\server\endpoints\system.js:226:32
    at Layer.handle [as handle_request] (C:\Users\86134\Desktop\workspace\anything-llm\server\node_modules\express\lib\router\layer.js:95:5)
    at next (\anything-llm\server\node_modules\express\lib\router\route.js:144:13)
    at validateMultiUserRequest (\anything-llm\server\utils\middleware\validatedRequest.js:85:3)
    at async validatedRequest (\anything-llm\server\utils\middleware\validatedRequest.js:9:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by shatfield4** [comment]
Hi, please follow the instructions in the [README here](https://github.com/Mintplex-Labs/anything-llm?tab=readme-ov-file#how-to-setup-for-development) and ensure it runs properly in development before trying to run this in prod.

**Comment by timothycarambat** [comment]
The root cause is you did not define `STORAGE_DIR` as an environment variable for prodution
