### ISSUE TITLE
Select Azure embedding and upload file with error message Cannot have chunkOverlap >= chunkSize

### ISSUE THREAD

**Issue by Rosejacka** [Mintplex-Labs/anything-llm#483]
Error: Cannot have chunkOverlap >= chunkSize
    at new TextSplitter (/app/server/node_modules/langchain/dist/text_splitter.cjs:46:19)
    at new RecursiveCharacterTextSplitter (/app/server/node_modules/langchain/dist/text_splitter.cjs:222:9)
    at Object.addDocumentToNamespace (/app/server/utils/vectorDbProviders/chroma/index.js:181:28)
    at async Object.addDocuments (/app/server/models/documents.js:56:26)
    at async /app/server/endpoints/workspaces.js:162:33
addDocumentToNamespace Cannot have chunkOverlap >= chunkSize
Failed to vectorize custom-documents/.txt-a85836a7-6c55-4111-9119-83dfc317d23d.json

There is no problem selecting Azure openai for the LLM model, while selecting the already installed Chrome for the database

**Comment by shatfield4** [comment]
Hi @Rosejacka! Could you give me some details about how you are running AnythingLLM? Are you running this in docker or just running it locally? Also let me know what OS you are using where you are getting this error.

**Comment by Rosejacka** [comment]
Hi @shatfield4 ! I deployed and ran it on Docker on Linux. I pulled and started the image according to the official documentation and successfully started it. I installed Chroma as the local storage vector database, and LLM, including embedding, was selected on Azure

**Comment by Rosejacka** [comment]
@shatfield4 Supplement all error messages! Thank! 

Adding new vectorized document into namespace playground
Error: Cannot have chunkOverlap >= chunkSize
    at new TextSplitter (/app/server/node_modules/langchain/dist/text_splitter.cjs:46:19)
    at new RecursiveCharacterTextSplitter (/app/server/node_modules/langchain/dist/text_splitter.cjs:222:9)
    at Object.addDocumentToNamespace (/app/server/utils/vectorDbProviders/chroma/index.js:181:28)
    at async Object.addDocuments (/app/server/models/documents.js:56:26)
    at async /app/server/endpoints/workspaces.js:162:33
addDocumentToNamespace Cannot have chunkOverlap >= chunkSize
Failed to vectorize custom-documents/Activiti.pdf-f17cb289-289a-4b34-a919-3cea548a5d3f.json
[TELEMETRY SENT] {
  event: 'documents_embedded_in_workspace',
  distinctId: 'a30932de-259e-401c-a040-05be1be2b2ab',
  properties: {
    LLMSelection: 'azure',
    Embedder: 'azure',
    VectorDbSelection: 'chroma'
  }
}

**Comment by timothycarambat** [comment]
@Rosejacka Thanks for the error log, can you confirm which commit you are on? We patched this yesterday on commit `049bfa14cbbd44acf95d735f5fdf14cfc52e53fe`, so if you are before that commit pulling to the most recent image and retrying embedding you should be good now!
