### ISSUE TITLE
[BUG] Handle special LLM tokens from unsanitized model responses

### ISSUE THREAD

**Issue by Joly0** [Mintplex-Labs/anything-llm#525]
Hey, i have a working ollama instance on my server with the falcon 7b model. I installed anything-llm and connected it to ollama, which worked without an issue. No i have this problem:
![grafik](https://github.com/Mintplex-Labs/anything-llm/assets/13993216/c1717314-eae1-49bc-9e05-7685ff714e15)

In the logs of anything-llm i can see this:
```
Error: The text contains a special token that is not allowed: <|endoftext|>
    at _Tiktoken.encode (/app/server/node_modules/js-tiktoken/dist/index.cjs:120:15)
    at TokenManager.countFromString (/app/server/utils/helpers/tiktoken.js:30:33)
    at /app/server/utils/helpers/tiktoken.js:44:28
    at Array.reduce (<anonymous>)
    at TokenManager.statsFrom (/app/server/utils/helpers/tiktoken.js:43:39)
    at messageArrayCompressor (/app/server/utils/helpers/chat/index.js:54:20)
    at OllamaAILLM.compressMessages (/app/server/utils/AiProviders/ollama/index.js:178:18)
    at OllamaAILLM.streamChat (/app/server/utils/AiProviders/ollama/index.js:129:33)
    at streamEmptyEmbeddingChat (/app/server/utils/chats/stream.js:181:39)
    at async streamChatWithWorkspace (/app/server/utils/chats/stream.js:54:12)
```

I am not sure, why "<|endoftext|>" is added to the end of the answer of ollama, but that is an issue for anything-llm

**Comment by timothycarambat** [comment]
Are you using a quantized model that is < 5-bit quant? The fact that it includes its `<|endtext|>` in its response usually indicates a model that is rough around the edges.

This is still a bug and should be handled properly, but if the model is small or heavily quantized these odd behaviours happen more often.

A simple fix is send `/reset` in chat to reset the thread to remove that special token.

**Comment by Joly0** [comment]
Thanks for the answer. According to this  https://ollama.ai/library/falcon:7b  it should be 4-bit quant

**Comment by timothycarambat** [comment]
@Joly0 then getting weird tokens back in the response would be par for the course 😞 . I had this same issue when running a quantized model that is less than 5-bit. _if_ possible I would try one step up, but will be fixing this issue regardless
