### ISSUE TITLE
[BUG]: Unable to fetch content from website

### ISSUE THREAD

**Issue by ashigup6** [Mintplex-Labs/anything-llm#719]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Getting below error:

getPageContent failed! Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///app/collector/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:260:27)
    at ChromeLauncher.executablePath (file:///app/collector/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:197:25)
    at ChromeLauncher.computeLaunchArguments (file:///app/collector/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:91:37)
    at async ChromeLauncher.launch (file:///app/collector/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:53:28)
    at async PuppeteerWebBaseLoader._scrape (/app/collector/node_modules/langchain/dist/document_loaders/web/puppeteer.cjs:42:25)
    at async PuppeteerWebBaseLoader.load (/app/collector/node_modules/langchain/dist/document_loaders/web/puppeteer.cjs:74:22)
    at async getPageContent (/app/collector/processLink/convert/generic.js:64:18)
    at async scrapeGenericUrl (/app/collector/processLink/convert/generic.js:11:19)
    at async processLink (/app/collector/processLink/index.js:6:10)
    at async /app/collector/index.js:56:49

**Comment by timothycarambat** [comment]
What version tag are you on?
Is the machine running amd64 or arm64 version of the image?
What underlying operating system are you on?
Did you run the docker image with the `--cap-add=SYS_ADMIN` option?

**Comment by ashigup6** [comment]
There was a permission issue and its resolved now. Thank you.
